- run: node src/index.js
        env:
          # Keep these as secrets (Security)
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MONGO_URI: ${{ secrets.MONGO_URI }}
          SCRAPER_API_KEY: ${{ secrets.SCRAPER_API_KEY }}
          
          # Add these manually (Convenience)
          SEARCH_ROLES: "MERN Stack Developer, Backend Developer, Frontend Developer"
          KEYWORDS: "node,express,react,mongodb,javascript,java"
          LOCATION: "Remote,Work From Home"